version: '2'
services:
  electron:
    build: electron
    ports:
      - "5900"
    network_mode: host
    privileged: true
    restart: always
    depends_on:
      - photos
  vnc:
    build: vnc
    ports:
      - "80"
    network_mode: host
    privileged: true
    restart: always
  photos:
    privileged: true
    restart: always
    build: ./photos
    ports:
      - "8888:8888"